### ISSUE TITLE
jQuery change events firing repeatedly and without changing value

### ISSUE THREAD

**Issue by jamesmoralee** [creativetimofficial/ct-material-kit-pro#115]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Jquery change events should only fire when the field is changed.

# Current Behavior

Change events fire as soon as the user focuses on a textbox and repeatedly until the user clicks out of the field.

# Failure Information (for bugs)

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Attach a jquery change event handler to a text box. e.g:
    $("input").change(function () {
        alert('Change event fired')
    });
2. Click in the textbox
3. Note that the change event fires repeatedly even though the value has not been changed.

## Context

Using Google Chrome (67.0.3396.99) on Windows 10 Pro but seems to affect all major browsers.

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by groovemen** [comment]
Hello @jamesmoralee, 

Thank you for using our products, please check the following [link](https://github.com/FezVrasta/bootstrap-material-design/pull/1326) of **bootstrap material design** repo where this issue is solved. If you comment the bootstrap material design script from your project you'll see that the event won't fire repeatedly anymore.

All the best, Stefan

**Comment by jamesmoralee** [comment]
Hi Stefan,

Thanks, the patch worked for us.

regards,
James
