### ISSUE TITLE
Sliders v9.1.0 doesn't work on navbar bottom fixed

### ISSUE THREAD

**Issue by MarcinMiotk** [creativetimofficial/ct-material-kit-pro#121]
# Expected Behavior + Current Behavior + Steps to Reproduce

I use latest version of Material Kit Pro. The Slider doesn't work when I put it inside NAV fixed-bottom navbar. It works when I put it inside the other elements - for example main div.

```
<nav class="navbar fixed-bottom bg-dark">
...
                            <div id="theSlider" class="slider"></div>
...
</nav>
```

## Context

* Device: Mobile + Web + Anywhere
* Operating System: Android and Windows 10 Pro
* Browser and Version: Chrome, Firefox, Opera

**Comment by groovemen** [comment]
Hello @MarcinMiotk, 
Thank you for using our products, please share with us a link to your product to check for a solution because I reproduced it but and works just fine. Check the images from below:
<img width="1293" alt="screen shot 2018-09-10 at 12 40 36" src="https://user-images.githubusercontent.com/21063398/45289927-00e92000-b4f7-11e8-8d9e-013de955a95b.png">
<img width="1294" alt="screen shot 2018-09-10 at 12 40 28" src="https://user-images.githubusercontent.com/21063398/45289928-00e92000-b4f7-11e8-8f43-e8cf54d46140.png">

All the best, 
Stefan
