### ISSUE TITLE
Feature request: CSS colour variables

### ISSUE THREAD

**Issue by Schneckolinski** [creativetimofficial/ct-material-kit-pro#151]
Material Kit Pro v2.1.1 feature request

Support for **colour variables** in _material-kit.css_ as started to implement in _/scss/variables/_colors.scss_ to be set globally to allow for easy customisation of primary colours for buttons, shadows, hover effects and so on.

**Comment by groovemen** [comment]
Hello @Schneckolinski,

Thank you for using our products, I will ask you to be more specific about your issue. Until then please check our documentation: https://demos.creative-tim.com/material-kit-pro/docs/2.1/getting-started/build-tools.html. Also, please fill the required Issue Template:

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

All the best, 
Stefan
