### ISSUE TITLE
carousel-fade

### ISSUE THREAD

**Issue by loraxio** [creativetimofficial/ct-material-kit-pro#159]
# Expected Behavior
I expect to see the bootstrap .carousel-fade transition when adding that class to a carousel.

# Current Behavior
After adding carousel-fade to the classes for a carousel, only the slide transition shows

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. step 1
Add "carousel-fade" to the class of a carousel
2. step 2
Save the file
3. you get it...
No fade when previewing page in web browser

**Comment by groovemen** [comment]
Hello @loraxio, 

Thank you for using our products, As we know, our product is built over Bootstrap v4.0.0. In that version, carousel **crossfade** wasn't implemented, that's why it isn't working the **carousel-fade** transition. There will be 2 options, to create a separate file where you have to build the style for the **.carousel-fade** or go to `assets/scss/material-kit/bootstrap/scss/_carousel.scss` file and overwrite with the code from Bootstrap v4.4.1 (attached below). But, this will require to set multiple variables that are called in the new version of **_carousel.scss** file. I have also attached the variables file.
[Archive.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/4197244/Archive.zip)

Hope that information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by loraxio** [comment]
Very cool! Thanks! Since I JUST started building the site, now is a great time to make this change. 

-joshua

**Comment by loraxio** [comment]
> Hello @loraxio,
> 
> Thank you for using our products, As we know, our product is built over Bootstrap v4.0.0. In that version, carousel **crossfade** wasn't implemented, that's why it isn't working the **carousel-fade** transition. There will be 2 options, to create a separate file where you have to build the style for the **.carousel-fade** or go to `assets/scss/material-kit/bootstrap/scss/_carousel.scss` file and overwrite with the code from Bootstrap v4.4.1 (attached below). But, this will require to set multiple variables that are called in the new version of **_carousel.scss** file. I have also attached the variables file.
> [Archive.zip](https://github.com/creativetimofficial/ct-material-kit-pro/files/4197244/Archive.zip)
> 
> Hope that information helps you. Please let us know if we can help you with anything else.
> 
> All the best,
> Stefan

I had replaced the files, but the crossfade does not work still. http://2020newhgala.org I am still working on the site, so disregard the limited functionality. But the crossfade issue would be great to fix. Thanks for your help!

**Comment by groovemen** [comment]
Did you recompiled the SCSS after you have made the changes?
