### ISSUE TITLE
Uses SCSS Instead Of Proper Material Themes & React Components

### ISSUE THREAD

**Issue by m-sterspace** [creativetimofficial/ct-material-kit-pro#168]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I expect to be able to use a Material UI Theme Provider to change typography, colours, and global styling.

# Current Behavior

The current repository unnecessarily mixes in scss and bootstrap instead of using pure material / jss / react components. The result makes it impossible to theme properly, and creates confusion on where styling and conditional rendering should take place.

**Comment by EINazare** [comment]
Hello there, @m-sterspace ,

Thank you for your interest in working with our products.

> - [x] I'm reporting the issue to the correct repository (for multi-repository projects)

You've checked this from our ISSUE_TEMPLATE, but in your description and title, you speak about the Material UI Theme Provider and React.
The product at hand, Material Kit PRO (https://www.creative-tim.com/product/material-kit-pro), come with the following dependencies:

- Bootstrap
- Bootstrap Material Design
- HTML
- SCSS/CSS
- jQuery

As you can see, there is no mention of React, or Material-UI.

Our best guess, is that you are using Material Kit PRO React: https://www.creative-tim.com/product/material-kit-pro-react
The issue you are talking about is covered in our live docs here: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/tutorial
This is the exact page of the styles: https://demos.creative-tim.com/material-kit-pro-react/#/documentation/styles
As you will see, we mentions the fact that we are using JSS with the makeStyles function for the styling of the theme (we do not say anything about Material UI Theme Provider).
Also, each of the component from the left menu, at the very start, states where to find its styles, and the format of it (js - jss (makeStyles) or scss).
We've used both jss and scss, since some of our plugins to not make use of JSS, the same way Material-UI makes use, and we needed to somehow style them and look nice with this theme. If you want, you can delete the scss, and those plugins, but then you will no longer make use of those plugins.
Even though, if we were to make use of the Material UI Theme Provider, we would also keep the scss, for the above plugins mentioned.

We're sorry about this inconvenience, but we cannot do anything about it. 
If no more then 24 hours have passed since your purchase, you can ask for a refund if you are not satisfied with our product, if they have passed, we can exchange your purchase with another one of same value, or of higher value with difference on your part.

Once again, sorry for this inconvenience.

Best,
Manu
