### ISSUE TITLE
Cards overlap on top of open navbar

### ISSUE THREAD

**Issue by RedDuckss** [creativetimofficial/ct-material-kit-pro#21]
Just bought the UI kit and have been running some tests with it for a few days. I've found 3 bugs so far (2 of which have already been reported).

If you have a collapsible navbar and cards on the page, when the navbar opens it displays under the cards. Changing the z-index of the card fixes this issue, however this makes the links and buttons on the card un-clickable.

![bug](http://i.imgur.com/S22H9qz.gif)

**Comment by dragosct10** [comment]
Hi @RedDuckss! First I saw in the uploaded video that when you collapse the navbar-menu it disappear. Please go in your html page and remove the `id` attribute from the div with class `.navbar-collapse.collapse` because this `id` attribute is activating the Bootstrap Javascript and automatically navbar-collapse will receive the property with value `height: 0` and in this way the navbar-collapse disappear. Second, the cards from `MK Pro` don't have the property `z-index` on class `.card`, so you don't have to put this property on the cards. In this way the problem will be fixed I think. Please tell us if everything will is working fine! 

Regards,
Dragos

**Comment by RedDuckss** [comment]
> Hi @RedDuckss! First I saw in the uploaded video that when you collapse the navbar-menu it disappear. Please go in your html page and remove the id attribute from the div with class .navbar-collapse.collapse because this id attribute is activating the Bootstrap Javascript and automatically navbar-collapse will receive the property with value height: 0 and in this way the navbar-collapse disappear. Second, the cards from MK Pro don't have the property z-index on class .card, so you don't have to put this property on the cards. In this way the problem will be fixed I think. Please tell us if everything is working fine!
> 
> Regards,
Dragos

My navbar does not have an `id` attribute, so there is nothing for me to remove. Also several of the card components do indeed have `z-index` set, hence why I tried to change the `z-index` of the entire card class (rather than several components).
