### ISSUE TITLE
Are The Dropdowns In the Kit Able to be Selects

### ISSUE THREAD

**Issue by KatherineGraham** [creativetimofficial/ct-material-kit-pro#97]
Hey, I love the styles in the kit for dropdowns, I was wondering if there was a way to apply that same dropdown style to selects. From what I have seen the dropdowns in the material kit are only for linked navigation menus.

**Comment by dragosct10** [comment]
Hi, @KatherineGraham! Thank you for using our product. In the previous version of this product on BS3, the select was like the dropdowns, but we changed this because the select if was like the dropdown for example in a form with multiple inputs the select can be easily confused with a button so for this reason the select must look like an input. Regards, Dragos

**Comment by KatherineGraham** [comment]
Is there an easy way I could apply the dropdown styles to selects for my application? 

The designers want that look on the selects so I've been trying to wrestle it and I thought I would ask here.

**Comment by groovemen** [comment]
Hello @KatherineGraham, all you have to do is to set in HTML for the <select> tag the following attribute: **data-style="btn btn-primary btn-round"**. The selectpicker will look like this:

<img width="284" alt="screen shot 2018-07-04 at 16 20 09" src="https://user-images.githubusercontent.com/21063398/42279448-7b60daca-7fa6-11e8-8f69-2168498a31a1.png">


Best,
Stefan
